#!/usr/bin/perl
use warnings;
use strict;
use IO::Socket;

(my $host, my $port) = @ARGV;

die "No host specified\n" unless $host;

#do a tcp check if a port was specified else do icmp
if($port) {
	until( my $sock = new IO::Socket::INET (
			PeerAddr => $host,
			PeerPort => $port,
			Proto => 'tcp',
			Timeout => 2)){next;}

	alertup();

} else { #icmp
	#use systems ping utility because it is setuid root
	#and you don't want this script to be

	while(1) {
		system("ping -c 1 $host > /dev/null 2>&1");
		if($? eq 0) {
			alertup();
			last;
		} elsif ($? & 127) { #signal killed ping
			#die "Died from signal\n";
			exit(1);
		}
	}
}

sub alertup {
	if($ENV{'DISPLAY'}) {
		if(!fork) {
			system("xmessage -center $host is up");
		}
	} else { #DISPLAY not set
		print "$host is up\n";
	}
}
